export const deityDragonlanceOptions = [
    'Branchala',
    'Habbakuk',
    'Kiri-Jolith',
    'Majere',
    'Mishakal',
    'Paladine',
    'Solinari',
    'Gilean',
    'Reorx',
    'Shinare',
    'Sirrion',
    'Zivilyn',
    'Chislev',
    'Hiddukel',
    'Morgion',
    'Sargonnas',
    'Zeboim',
    'Chemosh',
    'Hiddukel',
    'Morgion',
    'Nuitari',
    'Sargonnas',
    'Takhisis',
    'Zeboim',
    'Chislev',
    'Habbakuk',
    'Majere',
    'Mishakal',
    'Solinari',
    'Branchala',
    'Gilean',
    'Kiri-Jolith',
    'Paladine',
    'Reorx',
    'Shinare',
    'Sirrion',
    'Zivilyn',
    'Chemosh',
    'Nuitari',
    'Takhisis',
  ] as const
  
export type DeityDragonlance = (typeof deityDragonlanceOptions)[number]
