import { CharacterClass } from './classes'

export type SavingThrowOption = (typeof savingThrowsOptions)[number]
export const savingThrowsOptions = ['Fortitude', 'Reflex', 'Will'] as const
export type SavingThrows = {[type in SavingThrowOption]: number}
export type SavingThrowsByLevel = {
  [level in number]: SavingThrows
}


export const savingThrowsByClassNameByLevel: { [className in CharacterClass['name']]: SavingThrowsByLevel } = {
  Fighter: {
    1: { Fortitude: 2, Reflex: 0, Will: 0 },
    2: { Fortitude: 3, Reflex: 0, Will: 0 },
    3: { Fortitude: 3, Reflex: 1, Will: 1 },
    4: { Fortitude: 4, Reflex: 1, Will: 1 },
    5: { Fortitude: 4, Reflex: 1, Will: 1 },
    6: { Fortitude: 5, Reflex: 2, Will: 2 },
    7: { Fortitude: 5, Reflex: 2, Will: 2 },
    8: { Fortitude: 6, Reflex: 2, Will: 2 },
    9: { Fortitude: 6, Reflex: 3, Will: 3 },
    10: { Fortitude: 7, Reflex: 3, Will: 3 },
    11: { Fortitude: 7, Reflex: 3, Will: 3 },
    12: { Fortitude: 8, Reflex: 4, Will: 4 },
    13: { Fortitude: 8, Reflex: 4, Will: 4 },
    14: { Fortitude: 9, Reflex: 4, Will: 4 },
    15: { Fortitude: 9, Reflex: 5, Will: 5 },
    16: { Fortitude: 10, Reflex: 5, Will: 5 },
    17: { Fortitude: 10, Reflex: 5, Will: 5 },
    18: { Fortitude: 11, Reflex: 6, Will: 6 },
    19: { Fortitude: 11, Reflex: 6, Will: 6 },
    20: { Fortitude: 12, Reflex: 6, Will: 6 },
  },
  Rogue: {
    1: { Fortitude: 0, Reflex: 2, Will: 0 },
    2: { Fortitude: 0, Reflex: 3, Will: 0 },
    3: { Fortitude: 1, Reflex: 3, Will: 1 },
    4: { Fortitude: 1, Reflex: 4, Will: 1 },
    5: { Fortitude: 1, Reflex: 4, Will: 1 },
    6: { Fortitude: 2, Reflex: 5, Will: 2 },
    7: { Fortitude: 2, Reflex: 5, Will: 2 },
    8: { Fortitude: 2, Reflex: 6, Will: 2 },
    9: { Fortitude: 3, Reflex: 6, Will: 3 },
    10: { Fortitude: 3, Reflex: 7, Will: 3 },
    11: { Fortitude: 3, Reflex: 7, Will: 3 },
    12: { Fortitude: 4, Reflex: 8, Will: 4 },
    13: { Fortitude: 4, Reflex: 8, Will: 4 },
    14: { Fortitude: 4, Reflex: 9, Will: 4 },
    15: { Fortitude: 5, Reflex: 9, Will: 5 },
    16: { Fortitude: 5, Reflex: 10, Will: 5 },
    17: { Fortitude: 5, Reflex: 10, Will: 5 },
    18: { Fortitude: 6, Reflex: 11, Will: 6 },
    19: { Fortitude: 6, Reflex: 11, Will: 6 },
    20: { Fortitude: 6, Reflex: 12, Will: 6 },
  },
  Cleric: {
    1: { Fortitude: 2, Reflex: 0, Will: 2 },
    2: { Fortitude: 3, Reflex: 0, Will: 3 },
    3: { Fortitude: 3, Reflex: 1, Will: 3 },
    4: { Fortitude: 4, Reflex: 1, Will: 4 },
    5: { Fortitude: 4, Reflex: 1, Will: 4 },
    6: { Fortitude: 5, Reflex: 2, Will: 5 },
    7: { Fortitude: 5, Reflex: 2, Will: 5 },
    8: { Fortitude: 6, Reflex: 2, Will: 6 },
    9: { Fortitude: 6, Reflex: 3, Will: 6 },
    10: { Fortitude: 7, Reflex: 3, Will: 7 },
    11: { Fortitude: 7, Reflex: 3, Will: 7 },
    12: { Fortitude: 8, Reflex: 4, Will: 8 },
    13: { Fortitude: 8, Reflex: 4, Will: 8 },
    14: { Fortitude: 9, Reflex: 4, Will: 9 },
    15: { Fortitude: 9, Reflex: 5, Will: 9 },
    16: { Fortitude: 10, Reflex: 5, Will: 10 },
    17: { Fortitude: 10, Reflex: 5, Will: 10 },
    18: { Fortitude: 11, Reflex: 6, Will: 11 },
    19: { Fortitude: 11, Reflex: 6, Will: 11 },
    20: { Fortitude: 12, Reflex: 6, Will: 12 },
  },
  Wizard: {
    1: { Fortitude: 0, Reflex: 0, Will: 2 },
    2: { Fortitude: 0, Reflex: 0, Will: 3 },
    3: { Fortitude: 1, Reflex: 1, Will: 3 },
    4: { Fortitude: 1, Reflex: 1, Will: 4 },
    5: { Fortitude: 1, Reflex: 1, Will: 4 },
    6: { Fortitude: 2, Reflex: 2, Will: 5 },
    7: { Fortitude: 2, Reflex: 2, Will: 5 },
    8: { Fortitude: 2, Reflex: 2, Will: 6 },
    9: { Fortitude: 3, Reflex: 3, Will: 6 },
    10: { Fortitude: 3, Reflex: 3, Will: 7 },
    11: { Fortitude: 3, Reflex: 3, Will: 7 },
    12: { Fortitude: 4, Reflex: 4, Will: 8 },
    13: { Fortitude: 4, Reflex: 4, Will: 8 },
    14: { Fortitude: 4, Reflex: 4, Will: 9 },
    15: { Fortitude: 5, Reflex: 5, Will: 9 },
    16: { Fortitude: 5, Reflex: 5, Will: 10 },
    17: { Fortitude: 5, Reflex: 5, Will: 10 },
    18: { Fortitude: 6, Reflex: 6, Will: 11 },
    19: { Fortitude: 6, Reflex: 6, Will: 11 },
    20: { Fortitude: 6, Reflex: 6, Will: 12 },
  },
}
