// Definition: Skills and their descriptions from D&D 3.5

import { AbilityName } from './abilities'

export const skillsOptions = [
  'Appraise',
  'Balance',
  'Bluff',
  'Climb',
  'Concentration',
  'Craft',
  'Decipher Script',
  'Diplomacy',
  'Disable Device',
  'Disguise',
  'Escape Artist',
  'Forgery',
  'Gather Information',
  'Handle Animal',
  'Heal',
  'Hide',
  'Intimidate',
  'Jump',
  'Knowledge Arcana',
  'Knowledge Architecture & Engineering',
  'Knowledge Dungeoneering',
  'Knowledge Geography',
  'Knowledge History',
  'Knowledge Local',
  'Knowledge Nature',
  'Knowledge Nobility & Royalty',
  'Knowledge Religion',
  'Knowledge The Planes',
  'Listen',
  'Move Silently',
  'Open Lock',
  'Perform',
  'Profession',
  'Ride',
  'Search',
  'Sense Motive',
  'Sleight of Hand',
  'Speak Language',
  'Spellcraft',
  'Spot',
  'Survival',
  'Swim',
  'Tumble',
  'Use Magic Device',
  'Use Rope',
] as const

export type SkillName = (typeof skillsOptions)[number]

export type Skill = {
  name: SkillName
  keyAbility: AbilityName | 'n/a'
  shortDescription: string
  link: string
}

export const skills: {[skillName in SkillName]: Skill} = {
  Appraise: {
    name: 'Appraise',
    keyAbility: 'Intelligence',
    shortDescription: 'Estimate the value of an item.',
    link: 'https://www.d20srd.org/srd/skills/appraise.htm',
  },
  Balance: {
    name: 'Balance',
    keyAbility: 'Dexterity',
    shortDescription: 'Keep your balance while walking on narrow or unstable surfaces.',
    link: 'https://www.d20srd.org/srd/skills/balance.htm',
  },
  Bluff: {
    name: 'Bluff',
    keyAbility: 'Charisma',
    shortDescription: 'Convince others of a falsehood or trick them with your words.',
    link: 'https://www.d20srd.org/srd/skills/bluff.htm',
  },
  Climb: {
    name: 'Climb',
    keyAbility: 'Strength',
    shortDescription: 'Ascend or descend vertical surfaces like walls or cliffs.',
    link: 'https://www.d20srd.org/srd/skills/climb.htm',
  },
  Concentration: {
    name: 'Concentration',
    keyAbility: 'Constitution',
    shortDescription: 'Maintain focus on an activity despite distractions or damage.',
    link: 'https://www.d20srd.org/srd/skills/concentration.htm',
  },
  Craft: {
    name: 'Craft',
    keyAbility: 'Intelligence',
    shortDescription: 'Create various items, from armor to weapons and more.',
    link: 'https://www.d20srd.org/srd/skills/craft.htm',
  },
  'Decipher Script': {
    name: 'Decipher Script',
    keyAbility: 'Intelligence',
    shortDescription: 'Understand and interpret ancient or unknown writings.',
    link: 'https://www.d20srd.org/srd/skills/decipherScript.htm',
  },
  Diplomacy: {
    name: 'Diplomacy',
    keyAbility: 'Charisma',
    shortDescription: 'Negotiate, influence others, and resolve disputes.',
    link: 'https://www.d20srd.org/srd/skills/diplomacy.htm',
  },
  'Disable Device': {
    name: 'Disable Device',
    keyAbility: 'Intelligence',
    shortDescription: 'Disable traps and sabotage devices.',
    link: 'https://www.d20srd.org/srd/skills/disableDevice.htm',
  },
  Disguise: {
    name: 'Disguise',
    keyAbility: 'Charisma',
    shortDescription: 'Change your appearance to look like someone else.',
    link: 'https://www.d20srd.org/srd/skills/disguise.htm',
  },
  'Escape Artist': {
    name: 'Escape Artist',
    keyAbility: 'Dexterity',
    shortDescription: 'Slip out of bonds or escape from tight spaces.',
    link: 'https://www.d20srd.org/srd/skills/escapeArtist.htm',
  },
  Forgery: {
    name: 'Forgery',
    keyAbility: 'Intelligence',
    shortDescription: 'Create or detect forged documents.',
    link: 'https://www.d20srd.org/srd/skills/forgery.htm',
  },
  'Gather Information': {
    name: 'Gather Information',
    keyAbility: 'Charisma',
    shortDescription: 'Collect information through casual conversation or gossip.',
    link: 'https://www.d20srd.org/srd/skills/gatherInformation.htm',
  },
  'Handle Animal': {
    name: 'Handle Animal',
    keyAbility: 'Charisma',
    shortDescription: 'Train and control animals, including taming wild creatures.',
    link: 'https://www.d20srd.org/srd/skills/handleAnimal.htm',
  },
  Heal: {
    name: 'Heal',
    keyAbility: 'Wisdom',
    shortDescription: 'Provide first aid, treat wounds, or revive the unconscious.',
    link: 'https://www.d20srd.org/srd/skills/heal.htm',
  },
  Hide: {
    name: 'Hide',
    keyAbility: 'Dexterity',
    shortDescription: 'Conceal yourself from others using cover or shadows.',
    link: 'https://www.d20srd.org/srd/skills/hide.htm',
  },
  Intimidate: {
    name: 'Intimidate',
    keyAbility: 'Charisma',
    shortDescription: 'Coerce or scare others into doing what you want.',
    link: 'https://www.d20srd.org/srd/skills/intimidate.htm',
  },
  Jump: {
    name: 'Jump',
    keyAbility: 'Strength',
    shortDescription: 'Leap great distances or clear obstacles.',
    link: 'https://www.d20srd.org/srd/skills/jump.htm',
  },
  'Knowledge Arcana': {
    name: 'Knowledge Arcana',
    keyAbility: 'Intelligence',
    shortDescription: 'Recall knowledge of magic and spellcraft.',
    link: 'https://www.d20srd.org/srd/skills/knowledge.htm#arcana',
  },
  'Knowledge Architecture & Engineering': {
    name: 'Knowledge Architecture & Engineering',
    keyAbility: 'Intelligence',
    shortDescription: 'Understand architectural principles and engineering.',
    link: 'https://www.d20srd.org/srd/skills/knowledge.htm#architectureAndEngineering',
  },
  'Knowledge Dungeoneering': {
    name: 'Knowledge Dungeoneering',
    keyAbility: 'Intelligence',
    shortDescription: 'Identify underground hazards and creatures.',
    link: 'https://www.d20srd.org/srd/skills/knowledge.htm#dungeoneering',
  },
  'Knowledge Geography': {
    name: 'Knowledge Geography',
    keyAbility: 'Intelligence',
    shortDescription: 'Understand lands, climates, and geographic features.',
    link: 'https://www.d20srd.org/srd/skills/knowledge.htm#geography',
  },
  'Knowledge History': {
    name: 'Knowledge History',
    keyAbility: 'Intelligence',
    shortDescription: 'Recall significant historical events and people.',
    link: 'https://www.d20srd.org/srd/skills/knowledge.htm#history',
  },
  'Knowledge Local': {
    name: 'Knowledge Local',
    keyAbility: 'Intelligence',
    shortDescription: 'Understand local customs, laws, and legends.',
    link: 'https://www.d20srd.org/srd/skills/knowledge.htm#local',
  },
  'Knowledge Nature': {
    name: 'Knowledge Nature',
    keyAbility: 'Intelligence',
    shortDescription: 'Recall information about animals, plants, and natural cycles.',
    link: 'https://www.d20srd.org/srd/skills/knowledge.htm#nature',
  },
  'Knowledge Nobility & Royalty': {
    name: 'Knowledge Nobility & Royalty',
    keyAbility: 'Intelligence',
    shortDescription: 'Understand noble hierarchies and royal lineages.',
    link: 'https://www.d20srd.org/srd/skills/knowledge.htm#nobilityAndRoyalty',
  },
  'Knowledge Religion': {
    name: 'Knowledge Religion',
    keyAbility: 'Intelligence',
    shortDescription: 'Recall details of religious practices and lore.',
    link: 'https://www.d20srd.org/srd/skills/knowledge.htm#religion',
  },
  'Knowledge The Planes': {
    name: 'Knowledge The Planes',
    keyAbility: 'Intelligence',
    shortDescription: 'Understand the nature of different planes of existence.',
    link: 'https://www.d20srd.org/srd/skills/knowledge.htm#thePlanes',
  },
  Listen: {
    name: 'Listen',
    keyAbility: 'Wisdom',
    shortDescription: 'Hear sounds and detect noise in your surroundings.',
    link: 'https://www.d20srd.org/srd/skills/listen.htm',
  },
  'Move Silently': {
    name: 'Move Silently',
    keyAbility: 'Dexterity',
    shortDescription: 'Move without making noise.',
    link: 'https://www.d20srd.org/srd/skills/moveSilently.htm',
  },
  'Open Lock': {
    name: 'Open Lock',
    keyAbility: 'Dexterity',
    shortDescription: 'Pick locks and open secured mechanisms.',
    link: 'https://www.d20srd.org/srd/skills/openLock.htm',
  },
  Perform: {
    name: 'Perform',
    keyAbility: 'Charisma',
    shortDescription: 'Entertain audiences with artistic or musical talents.',
    link: 'https://www.d20srd.org/srd/skills/perform.htm',
  },
  Profession: {
    name: 'Profession',
    keyAbility: 'Wisdom',
    shortDescription: 'Work in a particular field for financial gain.',
    link: 'https://www.d20srd.org/srd/skills/profession.htm',
  },
  Ride: {
    name: 'Ride',
    keyAbility: 'Dexterity',
    shortDescription: 'Handle and control a mount in various situations.',
    link: 'https://www.d20srd.org/srd/skills/ride.htm',
  },
  Search: {
    name: 'Search',
    keyAbility: 'Intelligence',
    shortDescription: 'Find hidden objects or traps through close examination.',
    link: 'https://www.d20srd.org/srd/skills/search.htm',
  },
  'Sense Motive': {
    name: 'Sense Motive',
    keyAbility: 'Wisdom',
    shortDescription: 'Discern someone’s true intentions or detect deception.',
    link: 'https://www.d20srd.org/srd/skills/senseMotive.htm',
  },
  'Sleight of Hand': {
    name: 'Sleight of Hand',
    keyAbility: 'Dexterity',
    shortDescription: 'Perform tricks and take small objects unnoticed.',
    link: 'https://www.d20srd.org/srd/skills/sleightOfHand.htm',
  },
  'Speak Language': {
    name: 'Speak Language',
    keyAbility: 'n/a',
    shortDescription: 'Learn and speak new languages.',
    link: 'https://www.d20srd.org/srd/skills/speakLanguage.htm',
  },
  Spellcraft: {
    name: 'Spellcraft',
    keyAbility: 'Intelligence',
    shortDescription: 'Identify and understand spells as they are cast.',
    link: 'https://www.d20srd.org/srd/skills/spellcraft.htm',
  },
  Spot: {
    name: 'Spot',
    keyAbility: 'Wisdom',
    shortDescription: 'Notice details or hidden creatures from afar.',
    link: 'https://www.d20srd.org/srd/skills/spot.htm',
  },
  Survival: {
    name: 'Survival',
    keyAbility: 'Wisdom',
    shortDescription: 'Live off the land, track creatures, and endure harsh environments.',
    link: 'https://www.d20srd.org/srd/skills/survival.htm',
  },
  Swim: {
    name: 'Swim',
    keyAbility: 'Strength',
    shortDescription: 'Move through water with skill and endurance.',
    link: 'https://www.d20srd.org/srd/skills/swim.htm',
  },
  Tumble: {
    name: 'Tumble',
    keyAbility: 'Dexterity',
    shortDescription: 'Perform acrobatic maneuvers to avoid attacks and obstacles.',
    link: 'https://www.d20srd.org/srd/skills/tumble.htm',
  },
  'Use Magic Device': {
    name: 'Use Magic Device',
    keyAbility: 'Charisma',
    shortDescription: 'Activate magic items without having the necessary requirements.',
    link: 'https://www.d20srd.org/srd/skills/useMagicDevice.htm',
  },
  'Use Rope': {
    name: 'Use Rope',
    keyAbility: 'Dexterity',
    shortDescription: 'Bind, tie, or manipulate rope effectively.',
    link: 'https://www.d20srd.org/srd/skills/useRope.htm',
  },
}
