import { CharacterClass, SpellcasterClasses } from './classes'

type SpellSlot = {
  base: number
  bonus?: number
}

export type SpellPerDay = {
  0: SpellSlot
  1: SpellSlot
  2: SpellSlot
  3: SpellSlot
  4: SpellSlot
  5: SpellSlot
  6: SpellSlot
  7: SpellSlot
  8: SpellSlot
  9: SpellSlot
}

export type SpellPerDayByLevel = {
  [level in number]: SpellPerDay
}

const bonusSpellsByAbilityModifier: { [modifier in number]?: number[] } = {
  0: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  1: [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
  2: [0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
  3: [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
  4: [0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
  5: [0, 2, 1, 1, 1, 1, 0, 0, 0, 0],
  6: [0, 2, 2, 1, 1, 1, 1, 0, 0, 0],
  7: [0, 2, 2, 2, 1, 1, 1, 1, 0, 0],
  8: [0, 2, 2, 2, 2, 1, 1, 1, 1, 0],
  9: [0, 3, 2, 2, 2, 2, 1, 1, 1, 1],
  10: [0, 3, 3, 2, 2, 2, 2, 1, 1, 1, 1],
}

export const spellsSlotsByClassNameByLevel: {
  [className in SpellcasterClasses]: SpellPerDayByLevel
} = {
  Wizard: {
    1: {
      0: { base: 3 },
      1: { base: 1 },
      2: { base: 0 },
      3: { base: 0 },
      4: { base: 0 },
      5: { base: 0 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    2: {
      0: { base: 4 },
      1: { base: 2 },
      2: { base: 0 },
      3: { base: 0 },
      4: { base: 0 },
      5: { base: 0 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    3: {
      0: { base: 4 },
      1: { base: 2 },
      2: { base: 1 },
      3: { base: 0 },
      4: { base: 0 },
      5: { base: 0 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    4: {
      0: { base: 4 },
      1: { base: 3 },
      2: { base: 2 },
      3: { base: 0 },
      4: { base: 0 },
      5: { base: 0 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    5: {
      0: { base: 4 },
      1: { base: 3 },
      2: { base: 2 },
      3: { base: 1 },
      4: { base: 0 },
      5: { base: 0 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    6: {
      0: { base: 4 },
      1: { base: 3 },
      2: { base: 3 },
      3: { base: 2 },
      4: { base: 0 },
      5: { base: 0 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    7: {
      0: { base: 4 },
      1: { base: 4 },
      2: { base: 3 },
      3: { base: 2 },
      4: { base: 1 },
      5: { base: 0 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    8: {
      0: { base: 4 },
      1: { base: 4 },
      2: { base: 3 },
      3: { base: 3 },
      4: { base: 2 },
      5: { base: 0 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    9: {
      0: { base: 4 },
      1: { base: 4 },
      2: { base: 4 },
      3: { base: 3 },
      4: { base: 2 },
      5: { base: 1 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    10: {
      0: { base: 4 },
      1: { base: 4 },
      2: { base: 4 },
      3: { base: 3 },
      4: { base: 3 },
      5: { base: 2 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    11: {
      0: { base: 4 },
      1: { base: 4 },
      2: { base: 4 },
      3: { base: 4 },
      4: { base: 3 },
      5: { base: 2 },
      6: { base: 1 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    12: {
      0: { base: 4 },
      1: { base: 4 },
      2: { base: 4 },
      3: { base: 4 },
      4: { base: 3 },
      5: { base: 3 },
      6: { base: 2 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    13: {
      0: { base: 4 },
      1: { base: 4 },
      2: { base: 4 },
      3: { base: 4 },
      4: { base: 4 },
      5: { base: 3 },
      6: { base: 2 },
      7: { base: 1 },
      8: { base: 0 },
      9: { base: 0 },
    },
    14: {
      0: { base: 4 },
      1: { base: 4 },
      2: { base: 4 },
      3: { base: 4 },
      4: { base: 4 },
      5: { base: 3 },
      6: { base: 3 },
      7: { base: 2 },
      8: { base: 0 },
      9: { base: 0 },
    },
    15: {
      0: { base: 4 },
      1: { base: 4 },
      2: { base: 4 },
      3: { base: 4 },
      4: { base: 4 },
      5: { base: 4 },
      6: { base: 3 },
      7: { base: 2 },
      8: { base: 1 },
      9: { base: 0 },
    },
    16: {
      0: { base: 4 },
      1: { base: 4 },
      2: { base: 4 },
      3: { base: 4 },
      4: { base: 4 },
      5: { base: 4 },
      6: { base: 3 },
      7: { base: 3 },
      8: { base: 2 },
      9: { base: 0 },
    },
    17: {
      0: { base: 4 },
      1: { base: 4 },
      2: { base: 4 },
      3: { base: 4 },
      4: { base: 4 },
      5: { base: 4 },
      6: { base: 4 },
      7: { base: 3 },
      8: { base: 2 },
      9: { base: 1 },
    },
    18: {
      0: { base: 4 },
      1: { base: 4 },
      2: { base: 4 },
      3: { base: 4 },
      4: { base: 4 },
      5: { base: 4 },
      6: { base: 4 },
      7: { base: 3 },
      8: { base: 3 },
      9: { base: 2 },
    },
    19: {
      0: { base: 4 },
      1: { base: 4 },
      2: { base: 4 },
      3: { base: 4 },
      4: { base: 4 },
      5: { base: 4 },
      6: { base: 4 },
      7: { base: 4 },
      8: { base: 3 },
      9: { base: 3 },
    },
    20: {
      0: { base: 4 },
      1: { base: 4 },
      2: { base: 4 },
      3: { base: 4 },
      4: { base: 4 },
      5: { base: 4 },
      6: { base: 4 },
      7: { base: 4 },
      8: { base: 4 },
      9: { base: 4 },
    },
  },
  Cleric: {
    1: {
      0: { base: 3 },
      1: { base: 1, bonus: 1 },
      2: { base: 0 },
      3: { base: 0 },
      4: { base: 0 },
      5: { base: 0 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    2: {
      0: { base: 4 },
      1: { base: 2, bonus: 1 },
      2: { base: 0 },
      3: { base: 0 },
      4: { base: 0 },
      5: { base: 0 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    3: {
      0: { base: 4 },
      1: { base: 2, bonus: 1 },
      2: { base: 1, bonus: 1 },
      3: { base: 0 },
      4: { base: 0 },
      5: { base: 0 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    4: {
      0: { base: 5 },
      1: { base: 3, bonus: 1 },
      2: { base: 2, bonus: 1 },
      3: { base: 0 },
      4: { base: 0 },
      5: { base: 0 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    5: {
      0: { base: 5 },
      1: { base: 3, bonus: 1 },
      2: { base: 2, bonus: 1 },
      3: { base: 1, bonus: 1 },
      4: { base: 0 },
      5: { base: 0 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    6: {
      0: { base: 5 },
      1: { base: 3, bonus: 1 },
      2: { base: 3, bonus: 1 },
      3: { base: 2, bonus: 1 },
      4: { base: 1, bonus: 1 },
      5: { base: 0 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    7: {
      0: { base: 6 },
      1: { base: 4, bonus: 1 },
      2: { base: 3, bonus: 1 },
      3: { base: 2, bonus: 1 },
      4: { base: 1, bonus: 1 },
      5: { base: 0 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    8: {
      0: { base: 6 },
      1: { base: 4, bonus: 1 },
      2: { base: 3, bonus: 1 },
      3: { base: 3, bonus: 1 },
      4: { base: 2, bonus: 1 },
      5: { base: 1, bonus: 1 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    9: {
      0: { base: 6 },
      1: { base: 4, bonus: 1 },
      2: { base: 4, bonus: 1 },
      3: { base: 3, bonus: 1 },
      4: { base: 2, bonus: 1 },
      5: { base: 1, bonus: 1 },
      6: { base: 0 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    10: {
      0: { base: 6 },
      1: { base: 4, bonus: 1 },
      2: { base: 4, bonus: 1 },
      3: { base: 3, bonus: 1 },
      4: { base: 3, bonus: 1 },
      5: { base: 2, bonus: 1 },
      6: { base: 1, bonus: 1 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    11: {
      0: { base: 6 },
      1: { base: 5, bonus: 1 },
      2: { base: 4, bonus: 1 },
      3: { base: 4, bonus: 1 },
      4: { base: 3, bonus: 1 },
      5: { base: 2, bonus: 1 },
      6: { base: 1, bonus: 1 },
      7: { base: 0 },
      8: { base: 0 },
      9: { base: 0 },
    },
    12: {
      0: { base: 6 },
      1: { base: 5, bonus: 1 },
      2: { base: 4, bonus: 1 },
      3: { base: 4, bonus: 1 },
      4: { base: 3, bonus: 1 },
      5: { base: 3, bonus: 1 },
      6: { base: 2, bonus: 1 },
      7: { base: 1, bonus: 1 },
      8: { base: 0 },
      9: { base: 0 },
    },
    13: {
      0: { base: 6 },
      1: { base: 5, bonus: 1 },
      2: { base: 5, bonus: 1 },
      3: { base: 4, bonus: 1 },
      4: { base: 4, bonus: 1 },
      5: { base: 3, bonus: 1 },
      6: { base: 2, bonus: 1 },
      7: { base: 1, bonus: 1 },
      8: { base: 0 },
      9: { base: 0 },
    },
    14: {
      0: { base: 6 },
      1: { base: 5, bonus: 1 },
      2: { base: 5, bonus: 1 },
      3: { base: 5, bonus: 1 },
      4: { base: 4, bonus: 1 },
      5: { base: 3, bonus: 1 },
      6: { base: 3, bonus: 1 },
      7: { base: 2, bonus: 1 },
      8: { base: 1, bonus: 1 },
      9: { base: 0 },
    },
    15: {
      0: { base: 6 },
      1: { base: 5, bonus: 1 },
      2: { base: 5, bonus: 1 },
      3: { base: 5, bonus: 1 },
      4: { base: 4, bonus: 1 },
      5: { base: 4, bonus: 1 },
      6: { base: 3, bonus: 1 },
      7: { base: 2, bonus: 1 },
      8: { base: 1, bonus: 1 },
      9: { base: 0 },
    },
    16: {
      0: { base: 6 },
      1: { base: 5, bonus: 1 },
      2: { base: 5, bonus: 1 },
      3: { base: 5, bonus: 1 },
      4: { base: 4, bonus: 1 },
      5: { base: 4, bonus: 1 },
      6: { base: 3, bonus: 1 },
      7: { base: 3, bonus: 1 },
      8: { base: 2, bonus: 1 },
      9: { base: 0 },
    },
    17: {
      0: { base: 6 },
      1: { base: 5, bonus: 1 },
      2: { base: 5, bonus: 1 },
      3: { base: 5, bonus: 1 },
      4: { base: 5, bonus: 1 },
      5: { base: 4, bonus: 1 },
      6: { base: 3, bonus: 1 },
      7: { base: 2, bonus: 1 },
      8: { base: 1, bonus: 1 },
      9: { base: 0 },
    },
    18: {
      0: { base: 6 },
      1: { base: 5, bonus: 1 },
      2: { base: 5, bonus: 1 },
      3: { base: 5, bonus: 1 },
      4: { base: 5, bonus: 1 },
      5: { base: 4, bonus: 1 },
      6: { base: 4, bonus: 1 },
      7: { base: 3, bonus: 1 },
      8: { base: 2, bonus: 1 },
      9: { base: 1, bonus: 1 },
    },
    19: {
      0: { base: 6 },
      1: { base: 5, bonus: 1 },
      2: { base: 5, bonus: 1 },
      3: { base: 5, bonus: 1 },
      4: { base: 5, bonus: 1 },
      5: { base: 5, bonus: 1 },
      6: { base: 4, bonus: 1 },
      7: { base: 3, bonus: 1 },
      8: { base: 2, bonus: 1 },
      9: { base: 1, bonus: 1 },
    },
    20: {
      0: { base: 6 },
      1: { base: 5, bonus: 1 },
      2: { base: 5, bonus: 1 },
      3: { base: 5, bonus: 1 },
      4: { base: 5, bonus: 1 },
      5: { base: 5, bonus: 1 },
      6: { base: 5, bonus: 1 },
      7: { base: 4, bonus: 1 },
      8: { base: 3, bonus: 1 },
      9: { base: 2, bonus: 1 },
    },
  },
}
